export type ChatModelInfo = {
  /** Model identifier sent to AI Gateway, e.g. workers-ai/@cf/... or openai/gpt-4o-mini. */
  id: string;
  /** Human-readable model name shown in the picker. */
  name: string;
  description: string;
  task: string;
  provider: string;
  contextWindow?: number;
  supportsImages: boolean;
  source: "cloudflare" | "ai-gateway" | "fallback";
  pricing?: ModelPricing;
};

export type ModelPricing = {
  inputPerMillion?: number;
  outputPerMillion?: number;
  cachedInputPerMillion?: number;
};

export const WORKERS_AI_PROVIDER_PREFIX = "workers-ai/";
export const DEFAULT_CHAT_MODEL = "workers-ai/@cf/zai-org/glm-4.7-flash";
export const DEFAULT_VISION_MODEL = "workers-ai/@cf/moonshotai/kimi-k2.6";

export const AI_GATEWAY_EXTERNAL_MODELS: ChatModelInfo[] = [
  {
    id: "openai/gpt-5.5-pro",
    name: "OpenAI GPT-5.5 Pro",
    description: "Latest OpenAI pro model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5.5",
    name: "OpenAI GPT-5.5",
    description: "Latest OpenAI general-purpose model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5.4-pro",
    name: "OpenAI GPT-5.4 Pro",
    description: "OpenAI pro model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5.4",
    name: "OpenAI GPT-5.4",
    description: "OpenAI GPT-5.4 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5.4-mini",
    name: "OpenAI GPT-5.4 Mini",
    description: "Smaller OpenAI GPT-5.4 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5.4-nano",
    name: "OpenAI GPT-5.4 Nano",
    description: "Smallest OpenAI GPT-5.4 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5.3-chat-latest",
    name: "OpenAI GPT-5.3 Chat Latest",
    description: "Latest GPT-5.3 chat alias via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5.2-pro",
    name: "OpenAI GPT-5.2 Pro",
    description: "OpenAI GPT-5.2 pro model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5.2",
    name: "OpenAI GPT-5.2",
    description: "OpenAI GPT-5.2 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5.2-chat-latest",
    name: "OpenAI GPT-5.2 Chat Latest",
    description: "Latest GPT-5.2 chat alias via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5.1",
    name: "OpenAI GPT-5.1",
    description: "OpenAI GPT-5.1 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5.1-chat-latest",
    name: "OpenAI GPT-5.1 Chat Latest",
    description: "Latest GPT-5.1 chat alias via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5-pro",
    name: "OpenAI GPT-5 Pro",
    description: "OpenAI GPT-5 pro model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5",
    name: "OpenAI GPT-5",
    description: "OpenAI GPT-5 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5-mini",
    name: "OpenAI GPT-5 Mini",
    description: "Smaller OpenAI GPT-5 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-5-nano",
    name: "OpenAI GPT-5 Nano",
    description: "Smallest OpenAI GPT-5 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-4.1",
    name: "OpenAI GPT-4.1",
    description: "OpenAI GPT-4.1 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-4.1-mini",
    name: "OpenAI GPT-4.1 Mini",
    description: "Smaller OpenAI GPT-4.1 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-4.1-nano",
    name: "OpenAI GPT-4.1 Nano",
    description: "Smallest OpenAI GPT-4.1 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "openai/gpt-4o",
    name: "OpenAI GPT-4o",
    description: "OpenAI flagship multimodal model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
    pricing: { inputPerMillion: 2.5, outputPerMillion: 10 },
  },
  {
    id: "openai/gpt-4o-mini",
    name: "OpenAI GPT-4o Mini",
    description: "Fast, cost-efficient OpenAI multimodal model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: true,
    source: "ai-gateway",
    pricing: { inputPerMillion: 0.15, outputPerMillion: 0.6 },
  },
  {
    id: "openai/o3-pro",
    name: "OpenAI o3 Pro",
    description: "OpenAI o3 pro reasoning model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "openai/o3",
    name: "OpenAI o3",
    description: "OpenAI o3 reasoning model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "openai/o4-mini",
    name: "OpenAI o4 Mini",
    description: "OpenAI o4 mini reasoning model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "openai/o3-mini",
    name: "OpenAI o3 Mini",
    description: "OpenAI o3 mini reasoning model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "openai/o1-pro",
    name: "OpenAI o1 Pro",
    description: "OpenAI o1 pro reasoning model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "openai/o1",
    name: "OpenAI o1",
    description: "OpenAI o1 reasoning model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "OpenAI",
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "anthropic/claude-opus-4-7",
    name: "Claude Opus 4.7",
    description: "Latest Anthropic Opus model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Anthropic",
    contextWindow: 1_000_000,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "anthropic/claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    description: "Latest Anthropic Sonnet model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Anthropic",
    contextWindow: 1_000_000,
    supportsImages: true,
    source: "ai-gateway",
    pricing: { inputPerMillion: 3, outputPerMillion: 15 },
  },
  {
    id: "anthropic/claude-opus-4-6",
    name: "Claude Opus 4.6",
    description: "Anthropic Opus model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Anthropic",
    contextWindow: 1_000_000,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "anthropic/claude-opus-4-5-20251101",
    name: "Claude Opus 4.5",
    description: "Anthropic Opus 4.5 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Anthropic",
    contextWindow: 200_000,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "anthropic/claude-haiku-4-5-20251001",
    name: "Claude Haiku 4.5",
    description: "Fast Anthropic Haiku model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Anthropic",
    contextWindow: 200_000,
    supportsImages: true,
    source: "ai-gateway",
    pricing: { inputPerMillion: 1, outputPerMillion: 5 },
  },
  {
    id: "anthropic/claude-sonnet-4-5-20250929",
    name: "Claude Sonnet 4.5",
    description: "Anthropic Sonnet 4.5 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Anthropic",
    contextWindow: 1_000_000,
    supportsImages: true,
    source: "ai-gateway",
    pricing: { inputPerMillion: 3, outputPerMillion: 15 },
  },
  {
    id: "anthropic/claude-opus-4-1-20250805",
    name: "Claude Opus 4.1",
    description: "Anthropic Opus 4.1 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Anthropic",
    contextWindow: 200_000,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "anthropic/claude-opus-4-20250514",
    name: "Claude Opus 4",
    description: "Anthropic Opus 4 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Anthropic",
    contextWindow: 200_000,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "anthropic/claude-sonnet-4-20250514",
    name: "Claude Sonnet 4",
    description: "Anthropic Sonnet 4 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Anthropic",
    contextWindow: 1_000_000,
    supportsImages: true,
    source: "ai-gateway",
    pricing: { inputPerMillion: 3, outputPerMillion: 15 },
  },
  {
    id: "google-ai-studio/gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    description: "Gemini 3.1 Pro Preview via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-3.1-pro-preview-customtools",
    name: "Gemini 3.1 Pro Preview Custom Tools",
    description: "Gemini 3.1 Pro Preview optimized for custom tool usage via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    description: "Gemini 3.1 Flash Lite Preview via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    description: "Gemini 3 Flash Preview via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview",
    description: "Gemini 3 Pro Preview via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-pro-latest",
    name: "Gemini Pro Latest",
    description: "Latest Gemini Pro release via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-flash-latest",
    name: "Gemini Flash Latest",
    description: "Latest Gemini Flash release via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-flash-lite-latest",
    name: "Gemini Flash-Lite Latest",
    description: "Latest Gemini Flash-Lite release via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    description: "Stable Gemini 2.5 Pro via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
    pricing: { inputPerMillion: 1.25, outputPerMillion: 10 },
  },
  {
    id: "google-ai-studio/gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    description: "Stable Gemini 2.5 Flash via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
    pricing: { inputPerMillion: 0.3, outputPerMillion: 2.5 },
  },
  {
    id: "google-ai-studio/gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash-Lite",
    description: "Stable Gemini 2.5 Flash-Lite via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    description: "Gemini 2.0 Flash via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-2.0-flash-001",
    name: "Gemini 2.0 Flash 001",
    description: "Stable Gemini 2.0 Flash via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash-Lite",
    description: "Gemini 2.0 Flash-Lite via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemini-2.0-flash-lite-001",
    name: "Gemini 2.0 Flash-Lite 001",
    description: "Stable Gemini 2.0 Flash-Lite via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 1_048_576,
    supportsImages: true,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemma-4-31b-it",
    name: "Gemma 4 31B IT",
    description: "Gemma 4 31B instruction-tuned model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 262_144,
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemma-4-26b-a4b-it",
    name: "Gemma 4 26B A4B IT",
    description: "Gemma 4 26B A4B instruction-tuned model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 262_144,
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemma-3-27b-it",
    name: "Gemma 3 27B",
    description: "Gemma 3 27B instruction-tuned model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 131_072,
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemma-3-12b-it",
    name: "Gemma 3 12B",
    description: "Gemma 3 12B instruction-tuned model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 32_768,
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemma-3-4b-it",
    name: "Gemma 3 4B",
    description: "Gemma 3 4B instruction-tuned model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 32_768,
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemma-3-1b-it",
    name: "Gemma 3 1B",
    description: "Gemma 3 1B instruction-tuned model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 32_768,
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemma-3n-e4b-it",
    name: "Gemma 3n E4B",
    description: "Gemma 3n E4B instruction-tuned model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 8_192,
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "google-ai-studio/gemma-3n-e2b-it",
    name: "Gemma 3n E2B",
    description: "Gemma 3n E2B instruction-tuned model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "Google AI Studio",
    contextWindow: 8_192,
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "deepseek/deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    description: "Fast DeepSeek V4 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "DeepSeek",
    supportsImages: false,
    source: "ai-gateway",
  },
  {
    id: "deepseek/deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    description: "Higher-capability DeepSeek V4 model via Cloudflare AI Gateway.",
    task: "Text Generation",
    provider: "DeepSeek",
    supportsImages: false,
    source: "ai-gateway",
  },
];

export const FALLBACK_CHAT_MODELS: ChatModelInfo[] = [
  {
    id: DEFAULT_CHAT_MODEL,
    name: "@cf/zai-org/glm-4.7-flash",
    description:
      "Fast multilingual Workers AI text generation model with function calling and reasoning support.",
    task: "Text Generation",
    provider: "Workers AI",
    contextWindow: 131_072,
    supportsImages: false,
    source: "fallback",
  },
  {
    id: DEFAULT_VISION_MODEL,
    name: "@cf/moonshotai/kimi-k2.6",
    description:
      "Frontier-scale Workers AI model with a large context window and vision support.",
    task: "Text Generation",
    provider: "Workers AI",
    contextWindow: 262_144,
    supportsImages: true,
    source: "fallback",
  },
  {
    id: "workers-ai/@cf/moonshotai/kimi-k2.5",
    name: "@cf/moonshotai/kimi-k2.5",
    description:
      "Large-context Workers AI text and vision model suitable for multimodal chat.",
    task: "Text Generation",
    provider: "Workers AI",
    contextWindow: 256_000,
    supportsImages: true,
    source: "fallback",
  },
  {
    id: "workers-ai/@cf/openai/gpt-oss-120b",
    name: "@cf/openai/gpt-oss-120b",
    description:
      "Open-weight reasoning model hosted on Workers AI for general-purpose text tasks.",
    task: "Text Generation",
    provider: "Workers AI",
    contextWindow: 128_000,
    supportsImages: false,
    source: "fallback",
  },
  {
    id: "workers-ai/@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    name: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    description: "Fast Llama 3.3 70B instruct model hosted on Workers AI.",
    task: "Text Generation",
    provider: "Workers AI",
    supportsImages: false,
    source: "fallback",
  },
  ...AI_GATEWAY_EXTERNAL_MODELS,
];

export function toWorkersAiGatewayModelName(modelName: string) {
  return `${WORKERS_AI_PROVIDER_PREFIX}${modelName}`;
}

export function isGatewayChatModelName(value: unknown): value is string {
  return (
    typeof value === "string" &&
    value.length < 200 &&
    /^[a-z0-9][a-z0-9-]*\/[A-Za-z0-9@._:/+-]+$/.test(value)
  );
}

export function isWorkersAiGatewayModelName(value: string) {
  return value.startsWith(WORKERS_AI_PROVIDER_PREFIX);
}

export function stripWorkersAiGatewayPrefix(value: string) {
  return value.startsWith(WORKERS_AI_PROVIDER_PREFIX)
    ? value.slice(WORKERS_AI_PROVIDER_PREFIX.length)
    : value;
}
